FROM node:22-alpine AS builder

WORKDIR /app/dashboard

COPY app/dashboard/package*.json ./

RUN npm ci

COPY app/dashboard/ .
COPY app/shared ../shared

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dashboard/dist /usr/share/nginx/html

COPY app/dashboard/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx","-g","daemon off;"]