events {}

http {

    include /etc/nginx/mime.types;

    upstream dashboard {
        server dashboard:80;
    }

    upstream builder {
        server builder:80;
    }

    upstream server_api {
        server server:5000;
    }

    server {

        listen 80;

        location / {
            proxy_pass http://dashboard;
        }

    }

}